#!/bin/bash

set -exu

## loading .environment variables if exist
if [ -f .env ]; then . .env; fi
if [ -f ../.env ]; then . ../.env; fi
	
echo "Setting up global network for multiple projects (if not exists)"

if [ `docker network ls | grep -c network_main` != 1 ]; then 
	docker-compose -f ../network/docker-compose.yml up -d; 
else 
	echo "Network had already been set"; 
fi
