#!/bin/bash

set -exu

## loading .environment variables if exist
if [ -f .env ]; then . .env; fi
if [ -f ../.env ]; then . ../.env; fi

if [ ! -z "$1" -a "$1" == "ubuntu" ]; then

	echo $2 | sudo -S

	apt-get update
	apt-get upgrade -y

	apt-get install apt-transport-https ca-certificates
	sudo apt-key adv \
	--keyserver hkp://ha.pool.sks-keyservers.net:80 \
	--recv-keys 58118E89F3A912897C070ADBF76221572C52609D

	apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
	echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
	apt-get update

	apt-get install docker-engine
	service docker start

	curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
	chmod +x /usr/local/bin/docker-compose
fi

if [ ! -z "$1" -a "$1" == "debian" ]; then 
	
	apt-get update
	apt-get upgrade -y

	echo "deb http://ftp.debian.org/debian jessie-backports main" | tee /etc/apt/sources.list.d/docker.list

	apt-get install -y --no-install-recommends \
	     apt-transport-https \
	     ca-certificates \
	     curl \
	     software-properties-common

	curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

	apt-key fingerprint 0EBFCD88

	add-apt-repository \
	   "deb [arch=amd64] https://download.docker.com/linux/debian \
	   $(lsb_release -cs) \
	   stable"

	apt-get update
	
	if [ ! -z $PRODUCTION ]; then
		apt-cache madison docker-ce
		docker-ce | 17.03.0~ce-0~debian-$(lsb_release -cs) | https://download.docker.com/linux/debian jessie/stable amd64 Packages

		#apt-get install docker-ce=<VERSION_STRING> -y --no-install-recommends
	else
		apt-get install docker-ce -y --no-install-recommends
	fi
fi