#!/bin/bash

set -exu

## loading .environment variables if exist
if [ -f .env ]; then . .env; fi
if [ -f ../.env ]; then . ../.env; fi
	
docker-compose -f ../docker-compose.yml -f ../docker-compose.dev.yml up -d --build --remove-orphans