#!/bin/bash

set -exu

## loading .environment variables if exist
if [ -f .env ]; then . .env; fi
if [ -f ../.env ]; then . ../.env; fi

. ./init && docker-compose -f ../docker-compose.yml up -d --build

